version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myAPI:
    image: 'exponent-image'
    environment:
      - POSTGRES_PASSWD=${POSTGRES_PASSWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DRIVER_NAME=${POSTGRES_DRIVER_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_DISABLE=${POSTGRES_DISABLE}
      - POSTGRES_PUBLIC=${POSTGRES_PUBLIC}
      - SERVER_TIMEOUT=${SERVER_TIMEOUT}
      - POSTGRES_MAX_OPEN_CONN=${POSTGRES_MAX_OPEN_CONN}
      - POSTGRES_CONN_IDLE_TIME=${POSTGRES_CONN_IDLE_TIME}
      - POSTGRES_MIGRATION_HOST=${POSTGRES_MIGRATION_HOST}
      - SERVER_PORT=${SERVER_PORT}

    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

