version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myAPI:
    image: 'exponent-image'
    environment:
      - POSTGRES_PASSWD=${POSTGRES_PASSWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DRIVER_NAME=${POSTGRES_DRIVER_NAME}
      - POSTGRES_ENDPOINT=${POSTGRES_ENDPOINT}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}

    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

