package repoErrors

import (
	"fmt"
)

var (
	ErrNoFound                        = fmt.Errorf("results not found")
	ErrFailToSearch                   = fmt.Errorf("failed to search")
	ErrFailToGetSuggest               = fmt.Errorf("failed to get suggest")
	ErrFailToGetRecipes               = fmt.Errorf("failed to get recipes")
	ErrFailToGetRecipeByID            = fmt.Errorf("failed to get recipe by id")
	ErrFailToGetIngredientsRecipeByID = fmt.Errorf("failed to get ingredients recipe by id")
	ErrFailToEndCooking               = fmt.Errorf("failed to end cooking")
	ErrNoCurrentRecipe                = fmt.Errorf("no current recipe was found")
	ErrFailToStartCooking             = fmt.Errorf("failed to start cooking")
	ErrUserAlreadyCooking             = fmt.Errorf("user already cooking")
	ErrNoSuchRecipeWithID             = fmt.Errorf("no such recipe with id")
	ErrFailedToGetCurrentRecipe       = fmt.Errorf("failed to get current recipe")
	ErrFailedToUpdateRecipeStep       = fmt.Errorf("failed to update step cooking")
	ErrFailedToGetCurrentStepCooking  = fmt.Errorf("failed to get step cooking")
	ErrFailedToGetPrevStep            = fmt.Errorf("failed to get prev step")
	ErrFailedToGetNextStep            = fmt.Errorf("failed to get next step")
	ErrFailedToAddTimer               = fmt.Errorf("failed to add timer to recipe")
	ErrFailedToDeleteTimer            = fmt.Errorf("failed to delete timer")
	ErrFailedToGetTimers              = fmt.Errorf("failed to get timers")
	ErrFailedToGetRecipeStep          = fmt.Errorf("failed to get recipe step")
	ErrGetMaxMinCookingTime           = fmt.Errorf("err get max min cooking time")
	ErrToGetFilterValues              = fmt.Errorf("err to get filter values")
	ErrNoFoundImage                   = fmt.Errorf("no found image")
	ErrWithGenerating                 = fmt.Errorf("failed to generate recipe")
	ErrFailToGetRecipeByIDAndVersion  = fmt.Errorf("failed to get recipe by id and version")
	ErrWithModernization              = fmt.Errorf("failed to modern recipe")
	ErrWithUpdateVersion              = fmt.Errorf("failed to update version")
	ErrFailToCreateSession            = fmt.Errorf("fail to create session")
	ErrFailToGetUser                  = fmt.Errorf("fail to get user")
	ErrFailToDeleteSession            = fmt.Errorf("fail to delete session")
	ErrFailToUserIDBySessionID        = fmt.Errorf("fail to get userID by sessionID")
	ErrFailToCreateUser               = fmt.Errorf("fail to create user")
	ErrUserWithThisLoginAlreadyExists = fmt.Errorf("user with this login already exists")
	ErrFailToDeleteUser               = fmt.Errorf("fail to delete user")
	ErrLoginAlreadyUsed               = fmt.Errorf("login already used by other user")
	ErrFailToUpdateUser               = fmt.Errorf("fail to update user")
	ErrUserNotFound                   = fmt.Errorf("user not found")
	ErrFailedToGetToken               = fmt.Errorf("failed to get token")
	ErrFailedToGetDataByToken         = fmt.Errorf("failed to get data by token")
	ErrFailedToUnmarshalJSON          = fmt.Errorf("failed to unmarshal data")
	ErrFailToCreateVKUser             = fmt.Errorf("fail to create vk user")
	ErrUserNotAuth                    = fmt.Errorf("user not authenticated")
	ErrAllKeysAreUsing                = fmt.Errorf("all API keys are using")
)
