package internalerrors

import (
	"fmt"
)

var (
	ErrNoFound                           = fmt.Errorf("results not found")
	ErrFailToSearch                      = fmt.Errorf("failed to search")
	ErrFailToGetSuggest                  = fmt.Errorf("failed to get suggest")
	ErrFailToGetRecipes                  = fmt.Errorf("failed to get recipes")
	ErrZeroRowsGet                       = fmt.Errorf("not found any rows")
	ErrFailToGetRecipeByID               = fmt.Errorf("failed to get recipe by id")
	ErrFailToGetIngredientsRecipeByID    = fmt.Errorf("failed to get ingredients recipe by id")
	ErrFailToEndCooking                  = fmt.Errorf("failed to end cooking")
	ErrNoCurrentRecipe                   = fmt.Errorf("no current recipe was found")
	ErrFailToStartCooking                = fmt.Errorf("failed to start cooking")
	ErrUserAlreadyCooking                = fmt.Errorf("user already cooking")
	ErrNoSuchRecipeWithID                = fmt.Errorf("no such recipe with id")
	ErrFailedToGetCurrentRecipe          = fmt.Errorf("failed to get current recipe")
	ErrFailedToUpdateRecipeStep          = fmt.Errorf("failed to update step cooking")
	ErrFailedToGetCurrentStepCooking     = fmt.Errorf("failed to get step cooking")
	ErrFailedToGetPrevStep               = fmt.Errorf("failed to get prev step")
	ErrFailedToGetNextStep               = fmt.Errorf("failed to get next step")
	ErrFailedToAddTimer                  = fmt.Errorf("failed to add timer to recipe")
	ErrFailedToDeleteTimer               = fmt.Errorf("failed to delete timer")
	ErrFailedToGetTimers                 = fmt.Errorf("failed to get timers")
	ErrFailedToGetRecipeStep             = fmt.Errorf("failed to get recipe step")
	ErrGetMaxMinCookingTime              = fmt.Errorf("internalerrors get max min cooking time")
	ErrToGetFilterValues                 = fmt.Errorf("internalerrors to get filter values")
	ErrNoFoundImage                      = fmt.Errorf("no found image")
	ErrWithGenerating                    = fmt.Errorf("failed to generate recipe")
	ErrFailToGetRecipeByIDAndVersion     = fmt.Errorf("failed to get recipe by id and version")
	ErrWithModernization                 = fmt.Errorf("failed to modern recipe")
	ErrWithUpdateVersion                 = fmt.Errorf("failed to update version")
	ErrVersionNotFound                   = fmt.Errorf("version not found")
	ErrFailToCreateSession               = fmt.Errorf("fail to create session")
	ErrFailToGetUser                     = fmt.Errorf("fail to get user")
	ErrFailToDeleteSession               = fmt.Errorf("fail to delete session")
	ErrFailToUserIDBySessionID           = fmt.Errorf("fail to get userID by sessionID")
	ErrFailToCreateUser                  = fmt.Errorf("fail to create user")
	ErrUserWithThisLoginAlreadyExists    = fmt.Errorf("user with this login already exists")
	ErrFailToDeleteUser                  = fmt.Errorf("fail to delete user")
	ErrLoginAlreadyUsed                  = fmt.Errorf("login already used by other user")
	ErrFailToUpdateUser                  = fmt.Errorf("fail to update user")
	ErrUserNotFound                      = fmt.Errorf("user not found")
	ErrFailedToGetToken                  = fmt.Errorf("failed to get token")
	ErrFailedToGetDataByToken            = fmt.Errorf("failed to get data by token")
	ErrFailedToUnmarshalJSON             = fmt.Errorf("failed to unmarshal data")
	ErrFailToCreateVKUser                = fmt.Errorf("fail to create vk user")
	ErrUserNotAuth                       = fmt.Errorf("user not authenticated")
	ErrAllKeysAreUsing                   = fmt.Errorf("all API keys are using")
	ErrEmptyPassword                     = fmt.Errorf("password or newPassword is empty")
	ErrEmptySingUpData                   = fmt.Errorf("name or username or login or password is empty")
	ErrTooShortUsername                  = fmt.Errorf("username is too short for user")
	ErrTooShortSurname                   = fmt.Errorf("surname is too short for user")
	ErrEmptyName                         = fmt.Errorf("new name is empty")
	ErrEmptySurname                      = fmt.Errorf("new surname is empty")
	ErrEmptyLogin                        = fmt.Errorf("new login is empty")
	ErrEmptyVKLoginData                  = fmt.Errorf("device id or code or state is empty")
	ErrInvalidPassword                   = fmt.Errorf("invalid password")
	ErrTooEasyPassword                   = fmt.Errorf("too easy password")
	ErrDuplicateRow                      = fmt.Errorf("duplicate row")
	ErrRecipeWithThisIDDoesNotExist      = fmt.Errorf("recipe with this id does not exist")
	ErrFailedToAddFavoriteRecipe         = fmt.Errorf("failed to add favorite recipe")
	ErrFailedToDeleteFavoriteRecipe      = fmt.Errorf("failed to delete recipe")
	ErrZeroRowsDeleted                   = fmt.Errorf("zero rows deleted")
	ErrRecipeDoesNotExist                = fmt.Errorf("recipe does not exist")
	ErrParamNotFound                     = fmt.Errorf("param not found")
	ErrParamNotInteger                   = fmt.Errorf("param is not an integer")
	ErrGetZeroRowsWithPageGreaterThanOne = fmt.Errorf("get zero rows with page greater than one")
)
